---
title: "Proyecto"
author: "Jose Joaquín Rodríguez García"
date: "15 de diciembre de 2017"
output: pdf_document
---

```{r setup, include=FALSE}
library(readr)
```

Leemos las tablas con el número de personas extrangeras en Valencia por continente de procedencia: 

```{r}
tabla_country_2001<-as.data.frame(read_csv("tabla_paises_2001.csv"))
tabla_country_2004<-as.data.frame(read_csv("tabla_paises_2004.csv"))
tabla_country_2007<-as.data.frame(read_csv("tabla_paises_2007.csv"))
tabla_country_2010<-as.data.frame(read_csv("tabla_paises_2010.csv"))
tabla_country_2013<-as.data.frame(read_csv("tabla_paises_2013.csv"))
tabla_country_2017<-as.data.frame(read_csv("tabla_paises_2017.csv"))
```

Creamos una sola tabla con todos los datos:

```{r}
tabla_country_2000_2004<-merge(tabla_country_2001[,c(1,3)],tabla_country_2004, by = "X1",
      all = T, all.x = T, all.y = T,
      suffixes = c(".x",".y"),
      incomparables = NULL)
```

```{r}
tabla_country_2000_2007<-merge(tabla_country_2000_2004[,1:ncol(tabla_country_2000_2004)-1],tabla_country_2007, by = "X1",
      all = T, all.x = T, all.y = T,
      suffixes = c(".x",".y"))
```

```{r}
tabla_country_2000_2010<-merge(tabla_country_2000_2007[,1:ncol(tabla_country_2000_2007)-1],tabla_country_2010, by = "X1",
      all = T, all.x = T, all.y = T,
      suffixes = c(".x",".y"))
```

```{r}
tabla_country_2000_2013<-merge(tabla_country_2000_2010[,1:ncol(tabla_country_2000_2010)-1],tabla_country_2013, by = "X1",
      all = T, all.x = T, all.y = T,
      suffixes = c(".x",".y"))
```

```{r}
tabla_country_2000_2017<-merge(tabla_country_2000_2013[,1:ncol(tabla_country_2000_2013)],tabla_country_2017, by = "X1",
      all = T, all.x = T, all.y = T,
      suffixes = c(".x",".y"))
```


Preparamos los datos para hacer el gráfico:


```{r}
rownames(tabla_country_2000_2017)<-tabla_country_2000_2017[,1]
tabla_country_2000_2017<-tabla_country_2000_2017[2:ncol(tabla_country_2000_2017)]
```

```{r}
tabla_plot<-t(tabla_country_2000_2017)
```

```{r}
tabla_ggplot<-NULL
country_label<-colnames(tabla_plot)
year<-rep(2000,ncol(tabla_plot))
for(n in 1:nrow(tabla_plot)){
  country_number<-tabla_plot[n,]
  tabla_ggplot<-rbind(tabla_ggplot,data.frame(year,country_number,country_label))
}
#rep(rownames(tabla_plot)[1],ncol(tabla_plot))
```

```{r}
tabla_ggplot$year<-rep(c(2000:2017),each=ncol(tabla_plot))
rownames(tabla_ggplot)<-1:nrow(tabla_ggplot)
colnames(tabla_ggplot)<-c("Year","Total","Country")
```

Hacemos un gráfico para ver la evolución:

```{r}
require(ggplot2)
ggplot(tabla_ggplot,aes(x=Year,y=Total,color=Country))+geom_line()
```

```{r}
tabla_ggplot$Continent<-"NULL"

for(y in c("Romania","Italy","Bulgaria","France","Ukraine","United Kingdom","Russia","Germany","Armenia","Poland","Portugal","Netherlands","Lithuania","Ireland","Belgium","Hungary","Georgia","Sweden","Czech Republic","Moldova","Latvia","Austria","Greece","Swiss","Albania","Denmark","Slovakia")){
  for(n in 1:nrow(tabla_ggplot)){
    if(tabla_ggplot$Country[n]==y){
      tabla_ggplot$Continent[n]<-"Europe"
    }
  }
}
```

```{r}
for(y in c("Morocco","Nigeria","Algeria","Senegal","Mali","Equatorial Guinea","Ghana","Republic of Guinea","Cameroon","Egypt","Libya","Liberia","Mauritania","Sierra Leone")){
  for(n in 1:nrow(tabla_ggplot)){
    if(tabla_ggplot$Country[n]==y){
      tabla_ggplot$Continent[n]<-"Africa"
    }
  }
}
```

```{r}
for(y in c("United States","Mexico","Canada")){
  for(n in 1:nrow(tabla_ggplot)){
    if(tabla_ggplot$Country[n]==y){
      tabla_ggplot$Continent[n]<-"North America"
    }
  }
}
```

```{r}
for(y in c("Honduras","Cuba","Dominican Republic","Nicaragua","El Salvador","Guatemala","Panama")){
  for(n in 1:nrow(tabla_ggplot)){
    if(tabla_ggplot$Country[n]==y){
      tabla_ggplot$Continent[n]<-"Central America"
    }
  }
}
```

```{r}
for(y in c("Bolivia","Ecuador","Colombia","Argentina","Venezuela","Brazil","Paraguay","Uruguay","Peru","Chile")){
  for(n in 1:nrow(tabla_ggplot)){
    if(tabla_ggplot$Country[n]==y){
      tabla_ggplot$Continent[n]<-"South America"
    }
  }
}
```

```{r}
for(y in c("China","Pakistan","India","Syria","Philippines","Japan","Republic of Korea","Bangladesh","Lebanon","Jordan")){
  for(n in 1:nrow(tabla_ggplot)){
    if(tabla_ggplot$Country[n]==y){
      tabla_ggplot$Continent[n]<-"Asia"
    }
  }
}
```

```{r}
for(n in 1:nrow(tabla_ggplot)){
    if(tabla_ggplot$Country[n]=="New Zealand"){
      tabla_ggplot$Continent[n]<-"Oceania"
    }
  }
```