---
title: 'Creación tabla agencia tributaria por agrupaciones'
author: "Jose Joaquín Rodríguez García"
date: "14 de marzo de 2018"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(ff)
```

```{r}
tabla<-read.delim("D:/GoogleDrive/Hacker Civics/Proyecto Migrador/Importacion - Productos/Tablas creadas/tabla_productos_codigo_nc.csv", header = T, sep = ",",colClasses = c("numeric","character","character","character", "character", "character","numeric", "numeric","character"))
```

```{r}
names(tabla)<-c("Year","Flow","Province","Country","Product","Transport mode","Weight in KG","Value Cents Euro","Product category")
```

```{r}
group<-by(tabla$`Value Cents Euro`,tabla[,c("Year","Flow","Country","Product category")],sum,simplify = T)
```

```{r}
year<-NULL
flow<-NULL
Country<-NULL
ProducNumber<-NULL
```

```{r}
year<-rep(seq(2000,2016),48804)
flow<-rep(rep(c("E","I"),each=17),24402)
Country<-rep(rep(attr(group,"dimnames")$Country,each=34),98)
ProducNumber<-rep(attr(group,"dimnames")$`Product category`,each=8466)
```

```{r}
group<-as.list(group)
```

```{r}
matrix_prueba<-data.frame(1:length(year))
matrix_prueba$year<-year
matrix_prueba$flow<-flow
matrix_prueba$Country<-Country
matrix_prueba$Product<-ProducNumber
matrix_prueba$ValueCent<-group
```

```{r}
matrix_prueba<-matrix_prueba[,2:6]
names(matrix_prueba)<-c("Year","Flow","Country","Product category","Value Cents Euro")
```

```{r}
matrix_prueba$`Value Cents Euro`<-as.numeric(matrix_prueba$`Value Cents Euro`)
```

```{r}
matrix_prueba<-na.omit(matrix_prueba)
```

```{r}
group_i_e<-by(tabla$`Value Cents Euro`,tabla[,c("Year","Country","Product category")],sum,simplify = T)
```

```{r}
year<-rep(seq(2000,2016),24402)
flow<-rep("B",414834)
Country<-rep(rep(attr(group_i_e,"dimnames")$Country,each=17),98)
ProducNumber<-rep(attr(group_i_e,"dimnames")$`Product category`,each=4233)
```

```{r}
group_i_e<-as.list(group_i_e)
```

```{r}
matrix_i_e<-data.frame(1:length(year))
matrix_i_e$year<-year
matrix_i_e$flow<-flow
matrix_i_e$Country<-Country
matrix_i_e$Product<-ProducNumber
matrix_i_e$ValueCent<-group_i_e
```

```{r}
matrix_i_e<-matrix_i_e[,2:6]
names(matrix_i_e)<-c("Year","Flow","Country","Product category","Value Cents Euro")
```

```{r}
matrix_i_e$`Value Cents Euro`<-as.numeric(matrix_i_e$`Value Cents Euro`)
```

```{r}
matrix_i_e<-na.omit(matrix_i_e)
```

```{r}
matrix_final<-rbind(matrix_prueba,matrix_i_e)
```

```{r}
group_prod<-by(tabla$`Value Cents Euro`,tabla[,c("Year","Flow","Country")],sum,simplify = T)
```

```{r}
year<-NULL
flow<-NULL
Country<-NULL
ProducNumber<-NULL
```

```{r}
year<-rep(seq(2000,2016),498)
flow<-rep(rep(c("E","I"),each=17),249)
Country<-rep(attr(group_prod,"dimnames")$Country,each=34)
ProducNumber<-rep("777",each=8466)
```

```{r}
group_prod<-as.list(group_prod)
```

```{r}
matrix_prod<-data.frame(1:length(year))
matrix_prod$year<-year
matrix_prod$flow<-flow
matrix_prod$Country<-Country
matrix_prod$Product<-ProducNumber
matrix_prod$ValueCent<-group_prod
```

```{r}
matrix_prod<-matrix_prod[,2:6]
names(matrix_prod)<-c("Year","Flow","Country","Product category","Value Cents Euro")
```

```{r}
matrix_prod$`Value Cents Euro`<-as.numeric(matrix_prod$`Value Cents Euro`)
```

```{r}
matrix_prod<-na.omit(matrix_prod)
```

```{r}
matrix_final<-rbind(matrix_final,matrix_prod)
```

```{r}
group_total<-by(matrix_final$`Value Cents Euro`,matrix_final[,c("Year","Flow","Country")],sum,simplify = T)
```

```{r}
year<-NULL
flow<-NULL
Country<-NULL
ProducNumber<-NULL
```

```{r}
year<-rep(seq(2000,2016),249)
flow<-rep("B",4233)
Country<-rep(attr(group_total,"dimnames")$Country,each=17)
ProducNumber<-rep("777",each=4233)
```

```{r}
group_total<-as.list(group_total[,"B",])
```

```{r}
matrix_total<-data.frame(1:length(year))
matrix_total$year<-year
matrix_total$flow<-flow
matrix_total$Country<-Country
matrix_total$Product<-ProducNumber
matrix_total$ValueCent<-group_total
```

```{r}
matrix_total<-matrix_total[,2:6]
names(matrix_total)<-c("Year","Flow","Country","Product category","Value Cents Euro")
```

```{r}
matrix_total$`Value Cents Euro`<-as.numeric(matrix_total$`Value Cents Euro`)
```

```{r}
matrix_total<-na.omit(matrix_total)
```

```{r}
matrix_final<-rbind(matrix_final,matrix_total)
```

```{r}
write.csv(matrix_final,file="D:/GoogleDrive/Hacker Civics/GibHub/Proyecto Migrador/Preparación datos balanza comercial/Tablas generadas/tabla_por_grupos.csv",fileEncoding = "latin1",row.names=F)
```